### ISSUE TITLE
Error loading color scheme Packages/Theme - Flatgrammer.

### ISSUE THREAD

**Issue by TabMorty** [artifactdev/flatgrammer-theme#12]
Today I got a strange crash

On a fresh SublimeText3 install, Only packages inslalled are Package Control, and Flatgrammer theme. After working flawless for a few days, when I today started ST3, The theme was not activated properly (files are still in place). I exited SB3, started up again, same thing. 

View Console does not reveal any error either

I have not seen this problem before so I'm not sure if it's related to SB3 or the Theme, but things are not good.

The only way to remove, was to delete the theme files and manually remove from User settings

**Comment by artifactdev** [comment]
Hi, I don't think this problem is related to the theme itself. I think you should do a clean install again (also remove all application related config folders and files. But also try this version of package control: https://github.com/wbond/package_control/releases/tag/2.0.1-beta3

Maybe this can fix your issue.
